import type { Metadata } from "next";
import { Pixelify_Sans } from "next/font/google";
import "./globals.css";

const pixelify_sans = Pixelify_Sans({
  subsets: ["cyrillic", "latin"],
  variable: "--font-pixelify",
});

export const metadata: Metadata = {
  title: "StudyNook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-full flex flex-col ${pixelify_sans.className}`}>
        {children}
      </body>
    </html>
  );
}
